version: '3'
services:
  psql_db:
    image: postgres:latest
    build:
      context: ./db/relational/
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./db/relational/data:/var/lib/postgresql/data
    networks:
      - semanthica_net
    restart: always




networks:
  semanthica_net:
    driver: bridge