version: '3'
services:
  psql_db:
    image: postgres:latest
    build:
      context: ./db/relational/
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./db/relational/data:/var/lib/postgresql/data
    networks:
      - semanthica_net
    restart: always

  qdrant:
    image: qdrant/qdrant:v1.4.1
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./db/vector/data:/qdrant/storage
      - ./db/vector/snapshots:/qdrant/snapshots
    networks:
      - semanthica_net


networks:
  semanthica_net:
    driver: bridge