version: '3'
services:
  psql_db:
    image: postgres:15
    ports:
      - "5432:5432"
    networks:
      - semanthica_net
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

  qdrant:
    image: qdrant/qdrant:v1.4.1
    ports:
      - "6333:6333"
      - "6334:6334"
    networks:
      - semanthica_net

networks:
  semanthica_net:
    driver: bridge